name: Test Logging Workflow

on:
  workflow_dispatch: 

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Log a message
        run: echo "This is a test log message!"

      - name: Log environment variables
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"

      - name: Log current directory
        run: |
          echo "Current directory:"
          pwd
          echo "List of files:"
          ls -al

      - name: Log system info
        run: |
          echo "Operating System: $(uname -a)"
          echo "Date: $(date)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: bhargav0605/travel-api:${{ steps.date.outputs.date }}
